version: '3.9'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper2
    ports:
      - "2183:2182"
    networks:
      - aaa

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - aaa

  gateway:
    container_name: gateway
    build: .
    ports:
      - "2020:2020"
    networks:
      - aaa 
    depends_on:
      - zookeeper
      - kafka

networks:
  aaa:
    name: aaa
    driver: bridge
    external: true
