version: '3.9'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: booking_service
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - aaa

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6372:6379"
    networks:
      - aaa
    depends_on:
      - mongo

  booking-services:
    build: .
    container_name: booking_service1
    networks:
      - aaa
    ports:
      - "6666:6666"
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
  redis:

networks:
  aaa:
    name: aaa
    driver: bridge
    external: true
